### ISSUE TITLE
Opening/Closing HTML tags within if statements incorrectly flagged, unable to be ignored

### ISSUE THREAD

**Issue by 85SIXTY-Nick** [Shopify/prettier-plugin-liquid#90] opened 2022-08-25 23:51 UTC
**Describe the bug**
Valid HTML/Liquid is flagged when the HTML tag is opened but not closed within an if statement.  The  commend is not respected so the file has to be added to the .prettierignore

**Unformatted source**
```                                  {% if block.settings[b_img]  %}
                                  <div class="{{ b_img }} mega_imgcol">
                                    {% if block.settings[b_link] %}<a href="{{block.settings[b_link]}}">{% endif %}

                                      {% assign media = block.settings[b_img] %}
                                      {%- if media.aspect_ratio < 1 -%}
                                        <img src="{{ media | img_url: "550x"}}" alt="{{ media.alt | escape }}" width="{{ media.width }}" height="{{ media.height }}"/>
                                      {% endif %}
                                      {%- if media.aspect_ratio >= 1 and media.aspect_ratio < 2 -%}
                                        <img src="{{ media | img_url: "1080x"}}" alt="{{ media.alt | escape }}" width="{{ media.width }}" height="{{ media.height }}"/>
                                      {% endif %}
                                      {%- if media.aspect_ratio >= 2 -%}
                                        <img src="{{ media | img_url: "1800x"}}" alt="{{ media.alt | escape }}" width="{{ media.width }}" height="{{ media.height }}"/>
                                      {% endif %}

                                      <span>{{block.settings[b_head]}}</span>
                                    {% if block.settings[b_link] %}</a>{% endif %}
                                  </div>
                                  {% endif %}
```

**Expected output**
```{% if block.settings[b_img]  %}
                                  <div class="{{ b_img }} mega_imgcol">
 <!-- prettier-ignore --> 
                                    {% if block.settings[b_link] %}<a href="{{block.settings[b_link]}}">{% endif %}
```
This would result in that node being skipped and the rest of the file gets formatted.  I added the ignore comment in multiple places, including higher in the tree, but got the same result.  Ideally, this node would be able to be properly formatted too but enforcing the ignore comment would suffice for the time being.  

**Actual output**
[error] snippets/site-nav.liquid: LiquidHTMLParsingError: Attempting to close LiquidTag 'if' before HtmlElement 'a' was closed

**Debugging information**
 - macOS 12.5
- "@shopify/prettier-plugin-liquid": "^0.2.1",
- "prettier": "^2.7.1",
- node v18.7.0
- npm 8.15.0

**Additional context**
I have seen this with multiple tag types (a, div, etc).  This also was spotted when there are nested if statements with elements that don't have their closing tags in between statements.

My fix, for now, has been adding the impacted files to the ignore file.

Let me know if you need more information.  Thanks!

**Comment by charlespwd** [comment] 2022-08-29 12:40
:wave: Unfortunately, that's a [known issue](https://github.com/Shopify/prettier-plugin-liquid/blob/main/KNOWN_ISSUES.md#liquid-that-cant-be-prettier) I haven't found a fix for.

It's for the same reason you can't do this in JS and have it be pretty-printed:
```
// prettier-ignore
if ;{ hello

console.log('hi there');
```

The problem is that we can't parse your code into a [HTML + Liquid tree](https://github.com/Shopify/prettier-plugin-liquid/blob/main/HOW_IT_WORKS.md#how-we-can-handle-it).

And since the `prettier-ignore` rule targets the next "node" in the tree, we're kind of screwed here.

Now, I'm not closing this because we _might_ find a solution to parse this (e.g. adding "unclosed" nodes to the tree), but then we'd need to figure out a way to pretty print those since prettier-ignore is optional.

e.g. what should we do with this?
```liquid
{% # where should we indent next? %}
{% if media %}
  <media-wrapper>
    <div>
{% else %}
  <a>
{% endif %}
  Here?
    Here?
  What do we do with the next if statement?
  We can't know as we're printing that we're "closing" the unclosed.
  {% if media %}
    </div>
    </media-wrapper>
  {% else %}
    </a>
  {% endif %}
```

There is a solution, (as explained in [KNOWN_ISSUES.md](https://github.com/Shopify/prettier-plugin-liquid/blob/main/KNOWN_ISSUES.md)), and it involves turning your code into a pretty-printable tree:

```liquid
{% liquid
  if block.settings[b_link]
    assign wrapper = 'a'
  else
    assign wrapper = 'span'
  endif
%}
<{{ wrapper }} href={{ block.settings[b_link] }}>
  content that goes in the middle.
</{{ wrapper }}>
```

**Comment by 85SIXTY-Nick** [comment] 2022-08-30 00:44
Thanks for the details here

**Comment by pinguluk** [comment] 2023-03-15 16:03
I have the same problem in [announcement-bar.liquid](https://github.com/Shopify/dawn/blob/main/sections/announcement-bar.liquid)

![image](https://user-images.githubusercontent.com/16257821/225369031-de1b789f-e792-46e7-a8ae-9ccadb54cf6f.png)

**Comment by pinguluk** [comment] 2023-03-15 18:41
> @pingluk, you can set it to a variable. Careful not to quote swap. I know it's not ideal but that's one way until we fix this.
> 
> ```
> {% liquid
>   if cond
>     assign wrapper = "product-media"
>     assign props = "list=of props"
>   else
>     assign wrapper = "div"
>     assign props = ""
>   endif
> %}
> <{{ wrapper }} {{ props }}>
> 
> </{{ wrapper }}>
> ```

Yeah, instead of the variable, I've added a if else check for the rest of the props
![image](https://user-images.githubusercontent.com/16257821/225410313-e5c50db2-2964-4519-bc11-8b41709b47f6.png)

Now the problem is how I should handle if there are multiple tags/html elements
![image](https://user-images.githubusercontent.com/16257821/225410500-a47f947d-acbb-4c91-8aa4-e8a18916bf1d.png)

**Comment by pinguluk** [comment] 2023-03-15 20:49
Also if you have an if else statement at the start of the tag, you get an error
![Uploading image.png…]()

**Comment by pinguluk** [comment] 2023-03-17 16:18
> > Also another problem is how I should handle if there are multiple tags/html elements
> 
> Yeah for sure that one is hard. It's about balancing the desire to prevent unclosed nodes and intentional cases.
> 
> IMO, telling you that the tag is unclosed here is desired behaviour:
> 
> ```
> <body>
>   <div>
>     <div>
>       <a>
>         {% if cond %}
>         text <b>hi
>         {% endif %}
>       </a>
>     </div>
>   </div>
> </body>
> ```
> 
> But it isn't when you do it intentionally. The problem is finding a strategy that lets us do both:
> 
> 1. Tell you when you didn't close a tag
> 2. Not tell you when you didn't close a tag and it seems intentional
> 
> Also, there's something to be said about this technique being slightly dangerous. Since the condition is duplicated, code changes in one spot MUST be matched in the other condition or else you might break the entire DOM.

What if we check if the tag that can't be closed it's inside another block (for example *if* tag and condition) and then we find the nearest closing (supposed) matching tag, that's inside the same block with the same tag and condition?

e.g. 

```liquid
{%- if block.settings.link != blank -%}
<a href="{{ block.settings.link }}" class="announcement-bar__link link link--text focus-inset animate-arrow">
{%- endif -%}
  <div class="page-width">
    <p class="announcement-bar__message {{ block.settings.text_alignment }} h5">
      <span>{{ block.settings.text | escape }}</span>
      {%- if block.settings.link != blank -%}
      {% render 'icon-arrow' %}
      {%- endif -%}
    </p>
  </div>
{%- if block.settings.link != blank -%}
</a>
{%- endif -%}
```

because the **a** element it's inside the 
```liquid
{%- if block.settings.link != blank -%}
<a href="{{ block.settings.link }}" class="announcement-bar__link link link--text focus-inset animate-arrow">
{%- endif -%}
```
**if statement** block

then we will go down the code until we find the same the supposed closing **a** element, that's inside the same 
```liquid
{%- if block.settings.link != blank -%}
</a>
{%- endif -%}
```
**if statement** block ?

**Closed** 2023-05-19 18:59 UTC
Labels: bug
