### ISSUE TITLE
Odd formatting for some wrapping tags (<a>...</a>, <b>...</b>, etc)

### ISSUE THREAD

**Issue by chrish-d** [Shopify/prettier-plugin-liquid#42] opened 2022-08-03 10:18 UTC
**Describe the bug**
Sometimes when adding elements that wrap content, such as `<a>anchors</a>` or `<b>bold tags</b>` the formatting is odd and difficult-to-read. This mainly seems to happen when wrapping text, but doesn't seem to happen when wrapping another element like `<a><div>hey</div></a>`.

I'd expect lines containing a lot of parameters (`target`, `id`, `class`, etc) to wrap to multiple lines like in the first example, and lines containing only 2 or so parameters to be on one line.

**Expected output**
```liquid
<a
  target="_blank"
  href="/cart"
  class="something"
  id="something-else"
>
  Go to cart
</a>

<a target="_blank" href="/cart">
  Go to cart
</a>

<a target="_blank" href="/cart">
  <div>Go to cart</div>
</a>
```

**Actual output**
```liquid
<a
  target="_blank"
  href="/cart"
  class="something"
  id="something-else"
  >Go to cart</a
>

<a
  target="_blank"
  href="/cart"
  >Go to cart</a
>

<a
  target="_blank"
  href="/cart"
>
  <div>Go to cart</div>
</a>
```

**Debugging information**
 - OS [e.g. Windows, Mac, Linux] Mac
 - Version [e.g. 0.1.0] 12.2.1 (21D62)

**Comment by charlespwd** [comment] 2022-08-05 15:01
Hiya @chrish-d, that's actually expected behaviour. We do this to maintain the lack of whitespace. 

The gist is that `a` and `b` tags are have a CSS default value of `display: inline`. This means that whitespace inside those tags is meaningful. So when you write `<a>hi</a>` we consider the lack of whitespace between `<a>` and `hi` and `</a>` to be meaningful. So if we pretty-print your code, since one of our guiding principle is to [Prefer correctness over beautiful, unless opted-in](https://github.com/Shopify/prettier-plugin-liquid/blob/main/docs/principles/prefer-correctness.md), we need to _maintain_ that lack of whitespace.

We do that by Printing the closing `>` and opening `</a` on the same line as the text. The same way prettier's HTML plugin does. 

You can turn this off by setting the `htmlWhitespaceSensitivity` configuration to `ignore`, but be wary that if you blindly run the plugin on your theme, it might break your theme. 

Here's a couple of resources that go into this issue in more details:
- [Prettier's article on HTML whitespace sensitivity](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting)
- [Our own take on the same issue](https://github.com/Shopify/prettier-plugin-liquid/blob/main/docs/whitespace-handling.md)

**Closed by charlespwd** 2022-08-05 15:01 UTC
Labels: bug

**Comment by chrish-d** [comment] 2022-08-05 16:47
Thanks for clearing this up @charlespwd — it does make sense to strip the whitespace, even if it does mean it's less readable. Something I hadn't considered :)
